from __future__ import annotations

import re
from pathlib import Path

import pymupdf as fitz  # pymupdf (fitz API)

SUPPORTED_EXTS = {".pdf", ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".webp", ".bmp"}

DEFAULT_PROMPT = """You are a scholarly transcriber working with historical manuscripts in Western
European languages (Latin, Portuguese, French, Italian, Spanish, German, English).

You are transcribing ONE page of a multi-page document (page N of M).
Do NOT comment on the completeness, truncation, or fragmentary nature of the
text, and do NOT mention preceding or following pages. Transcribe only what is
visible on this page, exactly as it appears.

This prompt adds scholarly transcription rules to the palaeographer's base
prompt that precedes it (the base prompt defines the exact output format:
## Transcription, then ## Notes with ### Named entities — one entity per line
as a bullet — and ### Content summary). Keep that format unchanged:

1. Keep the original language and spelling. When you are confident about an
   abbreviation, expand it in square brackets, e.g. "dñs" -> "d[omi]n[u]s".
2. Preserve paragraphs, headings, and line breaks where they matter.
   Label marginal notes as `[margin: ...]` and interlinear additions as
   `[interlinear: ...]`.
3. Mark anything you cannot read: `[illegible]` for a few characters,
   `[illegible: N words]` for larger passages, `[damaged]`, `[hole]`, `[seal]`.
4. Never invent text you cannot see. If the page is blank, write `[blank page]`.
"""


def is_supported(name: str) -> bool:
    return Path(name).suffix.lower() in SUPPORTED_EXTS


def render_document(
    path: Path, out_dir: Path, dpi: int = 200, max_px: int = 1800, jpeg_quality: int = 88,
    prefix: str | None = None,
) -> list[Path]:
    """Render every page of a PDF (or a single image) to JPEG files, returning their paths.

    `prefix`, when given, replaces the `pNNN` page-index base name — used to
    give each image of a directory-of-images document a distinct file (its
    source stem) instead of overwriting p001.jpg."""
    out_dir.mkdir(parents=True, exist_ok=True)
    images: list[Path] = []
    with fitz.open(str(path)) as doc:
        for i, page in enumerate(doc):
            rect = page.rect
            zoom = dpi / 72.0
            if max_px and max(rect.width, rect.height) * zoom > max_px:
                zoom = max_px / max(rect.width, rect.height)
            pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
            name = f"{prefix}.jpg" if prefix else f"p{i + 1:03d}.jpg"
            out = out_dir / name
            out.write_bytes(pix.tobytes("jpeg", jpg_quality=jpeg_quality))
            images.append(out)
    return images


def page_count(path: Path) -> int:
    with fitz.open(str(path)) as doc:
        return len(doc)


# Stage kind -> prompt file stem. A collection can carry several prompts
# side by side: prompt.md (palaeographer), encoder.prompt.md (encoder
# detection rules), encoder-prompt-langextract.md (encoder fields + examples
# generated by the encoder helper — lives next to the source).
_KIND_FILE = {
    "prompt": "prompt",
    "encoder.prompt": "encoder.prompt",
    "encoder.prompt.langextract": "encoder-prompt-langextract",
}


def _kind_stem(kind: str) -> str:
    return _KIND_FILE.get(kind, kind)


def resolve_encoder_prompt(enc_file: Path, kind: str) -> tuple[str, str]:
    """Resolve a per-encoder stage prompt next to an encoder definition file.

    For encoders/<name>.md in a collection, the stage prompts live in the
    same folder as encoders/<name>.prompt.md (detection rules) and
    encoders/<name>.langextract.md (schema + examples). Falls back to the
    collection-level files (encoder.prompt.md / encoder-prompt-langextract.md)
    in the parent, then to "".
    """
    if kind == "encoder.prompt":
        local_stem = f"{enc_file.stem}.prompt"
        coll_stem = "encoder.prompt"
    elif kind == "encoder.prompt.langextract":
        local_stem = f"{enc_file.stem}.langextract"
        coll_stem = "encoder-prompt-langextract"
    else:
        return "", "none"
    local = enc_file.with_name(f"{local_stem}.md")
    if local.exists():
        return local.read_text(encoding="utf-8"), str(local)
    parent = enc_file.parent
    coll = parent.parent / f"{coll_stem}.md"
    if coll.exists():
        return coll.read_text(encoding="utf-8"), str(coll)
    return "", "none"


def prompt_candidates(
    stem: str,
    file_dir: Path,
    dropbox: Path,
    prompts_dir: Path,
    explicit: str | None = None,
    kind: str = "prompt",
) -> list[Path]:
    """Candidate prompt files in resolution order.

    `kind` qualifies the stage: "prompt" = palaeographer stage (file name
    `prompt.md`), "encoder.prompt" = encoder stage (file name
    `encoder.prompt.md`), "encoder.prompt.langextract" = encoder stage with
    file name `encoder-prompt-langextract.md`, etc. A document/collection
    can therefore carry per-stage prompts side by side.

    Order:
      1. explicit prompt file (--prompt flag)
      2. next to the document: <stem>.<kind>.md / <stem>.pdf.<kind>.md
      3. directory chain (nearest first):
           <dir>/<kind>.md, <dir>/<dirname>.<kind>.md,
           <parent>/<dirname>.<kind>.md (sidecar next to the directory),
         walking up to the dropbox root — this is how a collection-level prompt
         (e.g. dropbox/collections/COLX/prompt.md) applies to everything under
         it, and how a document-directory of images gets one prompt for all pages
      4. prompts dir: <stem>.<kind>.md
    """
    suffix = _kind_stem(kind)
    if explicit:
        p = Path(explicit)
        if not p.is_absolute():
            p = prompts_dir / explicit
        return [p]
    cands: list[Path] = [
        file_dir / f"{stem}.{suffix}.md",
        file_dir / f"{stem}.pdf.{suffix}.md",
    ]
    d = file_dir
    while True:
        cands.append(d / f"{suffix}.md")
        cands.append(d / f"{d.name}.{suffix}.md")
        if d != dropbox and dropbox in d.parents:
            cands.append(d.parent / f"{d.name}.{suffix}.md")
        if d == dropbox or dropbox not in d.parents:
            break
        d = d.parent
    cands.append(prompts_dir / f"{stem}.{suffix}.md")
    return cands


def resolve_prompt(
    stem: str,
    file_dir: Path,
    dropbox: Path,
    prompts_dir: Path,
    explicit: str | None = None,
    kind: str = "prompt",
) -> tuple[str, str]:
    """Return (prompt_text, source) for a document at file_dir.

    Resolution order: explicit --prompt, file-sidecar, directory/collection
    chain (nearest first), prompts/<stem>.<kind>.md, prompts/default_prompt.md,
    built-in default. `kind` selects the stage ("prompt" for the palaeographer
    stage, "encoder.prompt" for the encoder stage, ...).
    """
    for cand in prompt_candidates(stem, file_dir, dropbox, prompts_dir, explicit, kind):
        if cand.exists():
            return cand.read_text(encoding="utf-8"), str(cand)
    if kind == "prompt":
        default = prompts_dir / "default_prompt.md"
        if default.exists():
            return default.read_text(encoding="utf-8"), str(default)
        return DEFAULT_PROMPT, "builtin"
    return "", "none"


def compose_prompts(palaeographer_prompt: str, doc_prompt: str) -> str:
    """The palaeographer's base prompt comes BEFORE the document prompt."""
    pal = (palaeographer_prompt or "").strip()
    if not pal:
        return doc_prompt
    return f"{pal}\n\n---\n\n{doc_prompt}"


_NOTE_LABEL_RE = re.compile(
    r"^\s*[-*]?\s*\**\s*(Named entities|Content summary)\s*\**\s*:\s*(.*)$",
    re.IGNORECASE,
)
_NOTE_OTHER_RE = re.compile(
    r"^\s*[-*]?\s*\**\s*(Language|Script|Date clues?|Foliation[^:]*|Named entities|Content summary)\s*\**\s*:",
    re.IGNORECASE,
)


def _split_entities(value: str) -> list[str]:
    """Split an inline 'Named entities' value into bullet items.

    Splits on ';', '|', ',' and spaced hyphens (' - '), but only OUTSIDE
    parentheses, so parenthetical notes are kept intact
    (e.g. "Geylolo (likely Gading, a ruler of the region)" stays one item).
    """
    value = re.sub(r"^\s*[-*]\s+", "", value.strip())
    value = value.strip()
    if not value:
        return ["(none)"]
    parts: list[str] = []
    buf: list[str] = []
    depth = 0
    i = 0
    while i < len(value):
        ch = value[i]
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        if depth == 0 and (ch in (";", "|", ",") or value.startswith(" - ", i)):
            parts.append("".join(buf))
            buf = []
            i += 3 if value.startswith(" - ", i) else 1
            continue
        buf.append(ch)
        i += 1
    parts.append("".join(buf))
    items = [p.strip(" -") for p in parts if p.strip(" -")]
    return items or ["(none)"]


def format_notes(text: str) -> str:
    """Reformat a transcription: '- Named entities: …' becomes a
    '### Named entities' heading and '- Content summary: …' becomes a
    '### Content summary' heading.

    If the model wrote the value inline, it is split into a bullet list /
    paragraph; if it wrote bullets under the label, they are kept as-is.
    Lines that do not match are left untouched, so prompts with other
    output structures (JSON, tables, …) are unaffected.
    """
    if not text or ("Named entities" not in text and "Content summary" not in text):
        return text
    lines = text.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = _NOTE_LABEL_RE.match(line)
        if not m:
            out.append(line)
            i += 1
            continue
        label, value = m.group(1), m.group(2).strip()
        out.append(f"### {label}")
        # block = lines until the next Notes label or a heading
        j = i + 1
        while j < len(lines) and not _NOTE_LABEL_RE.match(lines[j]) and not lines[j].lstrip().startswith("#"):
            j += 1
        block = [b.strip() for b in lines[i + 1 : j] if b.strip()]
        if value:
            if label.lower() == "named entities":
                for item in _split_entities(value):
                    out.append(f"- {item}")
            else:
                out.append(value)
        for b in block:
            if label.lower() == "named entities" and not re.match(r"^\s*[-*]\s+", b):
                out.append(f"- {b}")
            else:
                out.append(b)
        i = j
    return "\n".join(out)


def build_page_prompt(file_prompt: str, filename: str, page_no: int, total: int) -> str:
    return f"Document: {filename}\nPage: {page_no} of {total}\n\n{file_prompt}"


# --------------------------------------------------------------------------- palaeographer selection

def palaeographer_candidates(stem: str, file_dir: Path, dropbox: Path) -> list[Path]:
    """Candidate 'palaeographer' files in resolution order.

    The file may be named 'palaeographer' with an optional '.txt' or '.md'
    extension (so it is easy to open/edit on desktop computers). Order per
    location: plain, then .txt, then .md; sidecar next to the document first,
    then <dir>/palaeographer walking up to the dropbox root (nearest wins).
    """
    exts = ("", ".txt", ".md")
    cands: list[Path] = [file_dir / f"{stem}.palaeographer{ext}" for ext in exts]
    d = file_dir
    while True:
        for ext in exts:
            cands.append(d / f"palaeographer{ext}")
        if d == dropbox or dropbox not in d.parents:
            break
        d = d.parent
    return cands


def resolve_palaeographer_id(
    stem: str, file_dir: Path, dropbox: Path, explicit: str | None = None
) -> tuple[str | None, str | None]:
    """Return (palaeographer_id, source) for a document, or (None, None) to
    fall back to the configured default. The id is the first non-empty line
    of the file; leading markdown markers ('# ', '- ', '* ') are tolerated."""
    if explicit:
        return explicit, f"flag:{explicit}"
    for cand in palaeographer_candidates(stem, file_dir, dropbox):
        if cand.exists():
            text = cand.read_text(encoding="utf-8").strip()
            if text:
                pal_id = re.sub(r"^[#\-*\s]+", "", text.splitlines()[0]).strip()
                if pal_id:
                    return pal_id, str(cand)
    return None, None


# --------------------------------------------------------------------------- editor selection

def editor_candidates(stem: str, file_dir: Path, dropbox: Path) -> list[Path]:
    """Candidate 'editor' files in resolution order (same chain as
    palaeographers): <stem>.editor sidecar, then <dir>/editor walking up to
    the dropbox root; plain, .txt and .md variants per location."""
    exts = ("", ".txt", ".md")
    cands: list[Path] = [file_dir / f"{stem}.editor{ext}" for ext in exts]
    d = file_dir
    while True:
        for ext in exts:
            cands.append(d / f"editor{ext}")
        if d == dropbox or dropbox not in d.parents:
            break
        d = d.parent
    return cands


def resolve_editor_id(
    stem: str, file_dir: Path, dropbox: Path, explicit: str | None = None
) -> tuple[str | None, str | None]:
    """Return (editor_id, source) for a document, or (None, None) for no editing."""
    if explicit:
        return explicit, f"flag:{explicit}"
    for cand in editor_candidates(stem, file_dir, dropbox):
        if cand.exists():
            text = cand.read_text(encoding="utf-8").strip()
            if text:
                ed_id = re.sub(r"^[#\-*\s]+", "", text.splitlines()[0]).strip()
                if ed_id:
                    return ed_id, str(cand)
    return None, None


# --------------------------------------------------------------------------- encoder selection

def encoder_candidates(stem: str, file_dir: Path, dropbox: Path) -> list[Path]:
    """Candidate 'encoder' files in resolution order (same chain as
    palaeographers/editors; plain, .txt and .md variants per location)."""
    exts = ("", ".txt", ".md")
    cands: list[Path] = [file_dir / f"{stem}.encoder{ext}" for ext in exts]
    d = file_dir
    while True:
        for ext in exts:
            cands.append(d / f"encoder{ext}")
        if d == dropbox or dropbox not in d.parents:
            break
        d = d.parent
    return cands


def resolve_encoder_id(
    stem: str, file_dir: Path, dropbox: Path, explicit: str | None = None
) -> tuple[str | None, str | None]:
    """Return (encoder_id, source) for a document, or (None, None) for none."""
    if explicit:
        return explicit, f"flag:{explicit}"
    for cand in encoder_candidates(stem, file_dir, dropbox):
        if cand.exists():
            text = cand.read_text(encoding="utf-8").strip()
            if text:
                enc_id = re.sub(r"^[#\-*\s]+", "", text.splitlines()[0]).strip()
                if enc_id:
                    return enc_id, str(cand)
    return None, None


def encoder_files_for(stem: str, file_dir: Path, dropbox: Path) -> list[Path]:
    """Encoder definition files for a document, in resolution order.

    Encoders live NEXT TO THE SOURCE so they travel with the documents:
    an `encoders/` subdirectory in the document's collection (nearest-wins,
    walking up to the dropbox root). Each *.md file in it is one encoder
    (e.g. encoders/table.md, encoders/biographies.md); a file whose name
    starts with '_' is ignored. Sidecar variants next to the document
    (<stem>.encoder.md) are also considered.
    """
    found: list[Path] = []
    seen: set[Path] = set()
    sidecars = [file_dir / f"{stem}.encoder.md", file_dir / f"{stem}.encoder.txt"]
    for c in sidecars:
        if c.exists():
            found.append(c)
            seen.add(c)
    d = file_dir
    while True:
        enc_dir = d / "encoders"
        if enc_dir.is_dir():
            for f in sorted(enc_dir.iterdir()):
                if not f.is_file() or f.name.startswith("_"):
                    continue
                if f.suffix.lower() not in (".md", ".txt"):
                    continue
                # stage prompts (name.prompt.md / name.langextract.md) are
                # companions of a definition, not definitions themselves
                if re.search(r"\.(prompt|langextract)\.(md|txt)$", f.name):
                    continue
                if f not in seen:
                    found.append(f)
                    seen.add(f)
        if d == dropbox or dropbox not in d.parents:
            break
        d = d.parent
    return found
